products/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::get('/', array('as'=>'home', 'uses'=> 'ProductController@index')); 
Route::resource('product', 'ProductController');
Route::resource('user', 'UserController');

products/app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() !== Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

products/app/models/Product.php
<?php
    class Product extends Eloquent{
        public static $rules = array(
            'name' => 'required|min:5',
            'price' => 'required'
        );
    }
?>

products/app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');
	
	public static $rules = array(
       	'username' => 'required|min:5',
        'password' => 'required'
    );
}

products/app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

products/app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

products/app/controllers/ProductController.php
<?php

class ProductController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{	
		$products = Product::all();
		return View::make('product.index', compact('products'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('product.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	 
	public function store()
	{
		$input = Input::all();
		$v = Validator::make($input, Product::$rules);
		
		if ($v->passes()) {	
			$product = new Product();
			$product->name = $input['name'];
			$product->price = $input['price'];
			$product->save();
			return Redirect::to(url('product'));
		} else {
			return Redirect::route('product.create')->withErrors($v);
		}
		
		
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$product = Product::find($id);
		return View::make('product.show', compact('product'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$product = Product::find($id);
		return View::make('product.edit', compact('product'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = Input::all();
		$product = Product::find($id);
		$v = Validator::make($input, Product::$rules);
		
		if ($v->passes()) {	
			$product->name = $input['name'];
			$product->price = $input['price'];
			$product->save();
			
			return Redirect::route('product.show', $product->id);
		} else {
			return Redirect::route('product.edit', $product->id)->withErrors($v);
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

products/app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('users.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$v = Validator::make($input, User::$rules);
		
		if ($v->passes()) {
			$password = $input['password'];
			$hashed = Hash::make($password);
			$user = new User;
			$user->username = $input['username'];
			$user->password = $hashed;
			$user->save();
			return Redirect::to(route('product.index'));
		} else {
			return Redirect::to(URL::previous())->withErrors($v);
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}
	
	public function login() {
		$userdata = array(
			'username' => Input::get('loginusername'),
			'password' => Input::get('loginpassword')
		);
		
		if (Auth::attempt($userdata)) {
			Session::put('login_error', '');
			return Redirect::to(URL::previous());
		} else {
			Session::put('login_error', 'Login failed');
			return Redirect::to(URL::previous())->withInput();
		}
	}
	
	public function logout() {
		Auth::logout();
		return Redirect::to(route('product.index'));
	}
}

products/app/views/layout.blade.php
<html>
<head>
    <title>Products</title>
</head>
<body>
    @if (Auth::check())
        {{ Auth::user()->username }} {{ link_to_route('user.logout', "(Sign out)") }}
    @else
        {{ Form::open(array('url' => secure_url('user/login'))) }}
            {{ Form::label('loginusername', 'Username: ') }}
            {{ Form::text('loginusername') }}
            {{ Form::label('loginpassword', 'Password: ') }}
            {{ Form::password('loginpassword') }}
            {{ Form::submit('Login') }}
            <a href = {{ route('user.create') }} >{{ Form::button('Create account') }}</a>
            {{ Form::label('error', Session::get('login_error')) }}
            {{ Session::put('login_error', ' ') }}
        {{ Form::close() }}
    @endif
    @yield('content')
</body>

products/app/views/product/create.blade.php
@extends('layout')

@section('content')
    {{ Form::open(array('action' => 'ProductController@store')) }}
    
        {{ Form::label('name', 'Product Name:') }}
        {{ Form::text('name') }}
        {{ $errors->first('name') }}
        <p></p>
        {{ Form::label('price', 'Price:') }}
        {{ Form::text('price') }}
        {{ $errors->first('price') }}
        <p></p>
        {{ Form::submit('Create') }}
        
    {{ Form::close() }}
@stop

products/app/views/product/edit.blade.php
@extends('layout')

@section('content')

    {{ Form::model($product, array('method' => 'PUT', 'route' => array('product.update', $product->id))) }}
    
        {{ Form::label('name', 'Product Name:') }}
        {{ Form::text('name') }}
        {{ $errors->first('name') }}
        <p></p>
        {{ Form::label('price', 'Price:') }}
        {{ Form::text('price') }}
        {{ $errors->first('price') }}
        <p></p>
        {{ Form::submit('Modify') }}
    
    {{ Form::close() }}
@stop

products/app/views/product/index.blade.php
@extends('layout')

@section('content')
    <ul>
        @foreach ($products as $product)
            <li>{{ link_to_route('product.show', $product->name, array($product->id)) }}</li>
        @endforeach
    </ul>
    {{ link_to_route('product.create', 'Create') }}
@stop

products/app/views/product/show.blade.php
@extends('layout')

@section('content')
    <h1>Product</h1>
    <p>Name: {{{$product->name}}}</p>
    <p>Price: ${{{$product->price}}}</p>
    <p>{{ link_to_route('product.edit', 'Edit', array($product->id)) }}</p>
    <p>{{ link_to_route('product.index', 'Home') }}</p>
@stop

products/app/views/users/create.blade.php
@extends('layout')

@section('content')
    {{ Form::open(array('url' => secure_url('user'))) }}
    
        {{ Form::label('username', 'New Username:') }}
        {{ Form::text('username') }}
        {{ $errors->first('username') }}
        <p></p>
        {{ Form::label('password', 'Password:') }}
        {{ Form::password('password') }}
        {{ $errors->first('password') }}
        <p></p>
        {{ Form::submit('Create') }}
        
    {{ Form::close() }}
@stop