2503ict-assign2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as'=>'home', 'uses'=> 'PostController@index'));
Route::get('home', array('as'=>'home', 'uses'=> 'PostController@index'));
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::get('user/search', array('as' => 'user.search', 'uses' => 'UserController@search'));
Route::get('user/friend/{friend}', array('as' => 'user.friend', 'uses' => 'UserController@friend'));
Route::resource('user', 'UserController');
Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');

2503ict-assign2/app/models/Post.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;

class Post extends Eloquent implements UserInterface, RemindableInterface, StaplerableInterface {

	use UserTrait, RemindableTrait, EloquentTrait;

	//The database table used by the model.
	protected $table = 'posts';
	
	public function __construct(array $attributes = array()) {
		$this->hasAttachedFile('image', [
			'styles' => [
			    'large' => '500x500',
				'medium' => '300x300',
				'thumb' => '100x100'
			]
		]);
		
		parent::__construct($attributes);
	}
	
	public function user() {
	    return $this->belongsTo('User', 'user_id', 'id');
	}
	
	public function comments() {
		return $this->hasMany('Comment');
	}
	
	public static $rules = array(
       	'title' => 'required',
        'message' => 'required',
        'privacy' => 'required'
    );
}

2503ict-assign2/app/controllers/PostController.php
<?php

class PostController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{	
		//select * from posts where user_id = $user->id
		//select * from posts  where privacy='public'
		//select * from posts inner join friends on (friends.reference_id = 8 or friends.referenced_id = 8) and (user_id = friends.reference_id or user_id = friends.referenced_id) where privacy='friends';
		//$user = Auth::user();
		//$friends = $user->friends;
		// $privateposts = Post::where('user_id', '=', $user->id, 'and', 'privacy', '=', 'private');
		// $publicposts = Post::where('privacy', '=', 'public')
		// $friendposts = Post::whereRaw("select * from posts inner join friends on (friends.reference_id = ? or friends.referenced_id = ?) and (user_id = friends.reference_id or user_id = friends.referenced_id) where privacy='friends'", array($user->id, $user->id));
		if (Auth::check()) {
			$posts = Post::orderBy('id', 'DESC')->paginate(10);
		} else {
			$posts = Post::where('privacy', '=', 'public')->orderBy('id', 'DESC')->paginate(10);
		}
	    $commentcount = array();
	    foreach ($posts as $post) {
	        $commentcount[$post->id] = count(Post::find($post->id)->comments);
	    }
		return View::make('post.home') -> withPosts($posts) -> withCommentcount($commentcount);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
	    $post = new Post;
		$input = Input::all();
		$v = Validator::make($input, Post::$rules);
		if (Auth::check()) {
			if ($v->passes()) {	
				$post->user_id = Auth::user()->id;
				$post->title = $input['title'];
				$post->message = $input['message'];
				$post->privacy = $input['privacy'];
				$post->save();
				
				return Redirect::route('post.show', $post->id);
			} else {
				return Redirect::route('post.edit', $post->id)->withErrors($v);
			}
		} else return Redirect::to(url('home'));
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$post = Post::find($id);
	    $comments = $post->comments()->paginate(8);
	    $commentcount = count($comments);
	    return View::make('post.show') -> withPost($post) -> withComments($comments) -> withCommentcount($commentcount);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$post = Post::find($id);
		$comments = $post->comments();
	    $commentcount = count($comments);
		return View::make('post.edit', compact('post', 'commentcount'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{	
		$post = Post::find($id);
		$input = Input::all();
		$v = Validator::make($input, Post::$rules);
		if (Auth::check()) {
			if ($v->passes()) {	
				$post->user_id = Auth::user()->id;
				$post->title = $input['title'];
				$post->message = $input['message'];
				$post->privacy = $input['privacy'];
				$post->save();
				
				return Redirect::route('post.show', $post->id);
			} else {
				return Redirect::route('post.edit', $post->id)->withErrors($v);
			}
		} else return Redirect::to(url('home'));
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Post::find($id)->delete();
	    return Redirect::to(url('home'));
	}
}

2503ict-assign2/app/views/post/edit.blade.php
@extends('master')

@section('title')
    <h1 style="text-align: center">Edit Post</h1>
@stop

@section('form')
    @if (Auth::check()) 
        {{ Form::model($post, array('method' => 'PUT', 'route' => array('post.update', $post->id))) }}
            {{ Form::label('title', 'Title: ', array('class' => 'block')) }}
            {{ Form::text('title', $post->title, array('class' => 'form-control')) }}
            {{ $errors->first('title') }}
            <p></p>
            {{ Form::label('message', 'Message: ', array('class' => 'block')) }}
            {{ Form::text('message', $post->message, array('class' => 'form-control')) }}
            {{ $errors->first('message') }}
            <p></p>
            <div>
                {{ Form::label('privacy', 'Private: ') }}
                {{ Form::radio('privacy', 'private', false, array('class' => 'postbtn')) }}
                <p></p>
                {{ Form::label('privacy', 'Friends: ') }}
                {{ Form::radio('privacy', 'friends', true, array('class' => 'postbtn')) }}
                <p></p>
                {{ Form::label('privacy', 'Public: ') }}
                {{ Form::radio('privacy', 'public', false, array('class' => 'postbtn')) }}
                <p></p>
                {{ $errors->first('privacy') }}
            </div>
            <p></p>
            {{ Form::submit('Save', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @else
        <h2>Please Login</h2>
        {{ Form::open(array('action' => 'UserController@login')) }}
            {{ Form::label('loginemail', 'Email: ', array('class' => 'block')) }}
            {{ Form::text('loginemail', '', array('class' => 'form-control', 'placeholder' => 'Email Address')) }}
            <p></p>
            {{ Form::label('loginpassword', 'Password: ', array('class' => 'block')) }}
            {{ Form::password('loginpassword', array('class' => 'form-control', 'placeholder' => 'Password')) }}
            <p></p>
            {{ Form::submit('Login', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @endif
@stop

@section('content')
    <div>
        <!--This is a quick and dirty method of allowing the entire div to become a link to the user's profile.-->
        <!--I'm not particularly happy with this solution, but something better would have taken longer, and with the new HTML5 specification, this is now legal.-->
        <a href="{{ route('user.show', $post->user_id) }}" style="display:block" > <div class='post'>
            <div class="imagediv">
               <!-- Small fragment of PHP for correcting the path returned from image->url() -->
                <!-- Path from this function is returned in format "/xxx/xxx/xxx.xxx", but file_exists requires a path without leading slash -->
                <!-- Used ltrim to edit -->
                <?php
                    $imageloc =  User::find($post->user_id)->image->url();
                    $fixedloc = ltrim($imageloc, '/');
                ?>
                @if ( File::exists($fixedloc))
                    <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image($fixedloc, "image", array("class" => "postimage")) }}</a>
                @else
                     <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image("images/noimage.jpg", "image", array("class" => "postimage")) }}</a>
                @endif
            </div>
            <div class="textwrap">
                <a href="{{ route('user.show', $post->user_id) }}"> <label class="username" style="color: black; cursor: pointer"> {{{Post::find($post->id)->user->firstname . ' ' . Post::find($post->id)->user->lastname}}} </label></a><br>
                <label class="title" style="color: black; cursor: pointer"> {{{$post->title}}} </label><br>
                <label class="message" style="color: black; cursor: pointer"> {{{$post->message}}} </label>
            </div>
            <div class="btn-group commentcount" style="position: absolute; margin-bottom: 10px;">
                <a href='{{{ url("post/$post->id") }}}'><button class="btn btn-info" type="button">Comments <span class="badge">{{{$commentcount}}}</span></button></a>
                <a href='{{{ url("post/$post->id/edit") }}}'><button class="btn btn-warning">Edit</button></a>
                {{ Form::open(array('route' => array('post.destroy', $post->id), 'method' => 'delete', 'class' => 'inline')) }}
                    <button type="submit" class="btn btn-danger">Delete</button>
                {{ Form::close() }}
            </div>
        </div> </a>
    </div>
@stop

2503ict-assign2/app/views/post/home.blade.php
@extends('master')

@section('title')
    <h1 style="text-align: center">Home Feed</h1>
@stop

@section('form')
    @if (Auth::check()) 
        {{ Form::open(array('action' => 'PostController@store', 'files' => true)) }}
            {{ Form::label('title', 'Title: ', array('class' => 'block')) }}
            {{ Form::text('title', '', array('class' => 'form-control', 'placeholder' => 'Title')) }}
            {{ $errors->first('title') }}
            <p></p>
            {{ Form::label('message', 'Message: ', array('class' => 'block')) }}
            {{ Form::text('message', '', array('class' => 'form-control', 'placeholder' => 'Message')) }}
            {{ $errors->first('message') }}
            <p></p>
            <div>
                {{ Form::label('privacy', 'Private: ') }}
                {{ Form::radio('privacy', 'private', false, array('class' => 'postbtn')) }}
                </br>
                {{ Form::label('privacy', 'Friends: ') }}
                {{ Form::radio('privacy', 'friends', true, array('class' => 'postbtn')) }}
                </br>
                {{ Form::label('privacy', 'Public: ') }}
                {{ Form::radio('privacy', 'public', false, array('class' => 'postbtn')) }}
                </br>
                {{ $errors->first('privacy') }}
            </div>
            <p></p>
            {{ Form::submit('Post', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @else
        <h2>Please Login</h2>
        {{ Form::open(array('action' => 'UserController@login')) }}
            {{ Form::label('loginemail', 'Email: ', array('class' => 'block')) }}
            {{ Form::text('loginemail', '', array('class' => 'form-control', 'placeholder' => 'Email Address')) }}
            <p></p>
            {{ Form::label('loginpassword', 'Password: ', array('class' => 'block')) }}
            {{ Form::password('loginpassword', array('class' => 'form-control', 'placeholder' => 'Password')) }}
            <p></p>
            {{ Form::submit('Login', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @endif
@stop

@section('content')
    <div>
        @foreach ($posts as $post)
            <div>
                <div class='post'>
                    <div class="imagediv">
                        <!-- Small fragment of PHP for correcting the path returned from image->url() -->
                        <!-- Path from this function is returned in format "/xxx/xxx/xxx.xxx", but file_exists requires a path without leading slash -->
                        <!-- Used ltrim to edit -->
                        <?php
                            $imageloc =  User::find($post->user_id)->image->url();
                            $fixedloc = ltrim($imageloc, '/');
                        ?>
                        @if ( File::exists($fixedloc))
                            <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image($fixedloc, "image", array("class" => "postimage")) }}</a>
                        @else
                             <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image("images/noimage.jpg", "image", array("class" => "postimage")) }}</a>
                        @endif
                    </div>
                    <div class="textwrap">
                        <a href="{{ route('user.show', $post->user_id) }}"> <label class="username" style="color: black; cursor: pointer"> {{{Post::find($post->id)->user->firstname . ' ' . Post::find($post->id)->user->lastname}}} </label></a><br>
                        <label class="title"> {{{$post->title}}} </label><br>
                        <label class="message"> {{{$post->message}}} </label>
                    </div>
                    <div class="btn-group commentcount" style="position: absolute; margin-bottom: 10px;">
                        <a href='{{{ url("post/$post->id") }}}'><button class="btn btn-info" type="button">Comments <span class="badge">{{{$commentcount[$post->id]}}}</span></button></a>
                        <a href='{{{ url("post/$post->id/edit") }}}'><button class="btn btn-warning">Edit</button></a>
                        {{ Form::open(array('route' => array('post.destroy', $post->id), 'method' => 'delete', 'class' => 'inline')) }}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        @endforeach
        {{ $posts->links() }}
    </div>
@stop

2503ict-assign2/app/views/post/show.blade.php
@extends('master')

@section('title')
    <h1 style="text-align: center">Comments</h1>
@stop


@section('form')
    @if (Auth::check()) 
        {{ Form::open(array('action' => 'CommentController@store', 'files' => true)) }}
            {{ Form::hidden('post_id', $post->id) }}
            {{ Form::label('message', 'Comment: ', array('class' => 'block')) }}
            {{ Form::text('message', '', array('class' => 'form-control', 'placeholder' => 'Comment')) }}
            {{ $errors->first('message') }}
            <p></p>
            {{ Form::submit('Comment', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @else
        <h2>Please Login</h2>
        {{ Form::open(array('action' => 'UserController@login')) }}
            {{ Form::label('loginemail', 'Email: ', array('class' => 'block')) }}
            {{ Form::text('loginemail', '', array('class' => 'form-control', 'placeholder' => 'Email Address')) }}
            <p></p>
            {{ Form::label('loginpassword', 'Password: ', array('class' => 'block')) }}
            {{ Form::password('loginpassword', array('class' => 'form-control', 'placeholder' => 'Password')) }}
            <p></p>
            {{ Form::submit('Login', array('class' => 'btn btn-primary postbtn')) }}
        {{ Form::close() }}
    @endif
@stop

@section('content')
    <div>
        <div>
            <div class='post'>
                <div class="imagediv">
                    <!-- Small fragment of PHP for correcting the path returned from image->url() -->
                    <!-- Path from this function is returned in format "/xxx/xxx/xxx.xxx", but file_exists requires a path without leading slash -->
                    <!-- Used ltrim to edit -->
                    <?php
                        $imageloc =  User::find($post->user_id)->image->url();
                        $fixedloc = ltrim($imageloc, '/');
                    ?>
                    @if ( File::exists($fixedloc))
                        <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image($fixedloc, "image", array("class" => "postimage")) }}</a>
                    @else
                         <a href="{{ route('user.show', $post->user_id) }}">{{ HTML::image("images/noimage.jpg", "image", array("class" => "postimage")) }}</a>
                    @endif
                </div>
                <div class="textwrap">
                    <a href="{{ route('user.show', $post->user_id) }}"> <label class="username" style="color: black; cursor: pointer"> {{{Post::find($post->id)->user->firstname . ' ' . Post::find($post->id)->user->lastname}}} </label></a><br>
                    <label class="title"> {{{$post->title}}} </label><br>
                    <label class="message"> {{{$post->message}}} </label>
                </div>
                <div class="btn-group commentcount" style="position: absolute; margin-bottom: 10px;">
                    <a href='{{{ url("post/$post->id") }}}'><button class="btn btn-info" type="button">Comments <span class="badge">{{{$commentcount}}}</span></button></a>
                    <a href='{{{ url("post/$post->id/edit") }}}'><button class="btn btn-warning">Edit</button></a>
                    {{ Form::open(array('route' => array('post.destroy', $post->id), 'method' => 'delete', 'class' => 'inline')) }}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
    <div>
        @foreach ($comments as $comment)
            <div>
                <div class='post'>
                    <div class="textwrap">
                        <a href="{{ route('user.show', $post->user_id) }}"> <label class="username" style="color: black; cursor: pointer"> {{{Comment::find($comment->id)->user->firstname . ' ' . Comment::find($comment->id)->user->lastname}}} </label></a><br>
                        <label class="message">{{{$comment->message}}} </label>
                    </div>
                    <div class="btn-group commentcount" style="position: absolute; margin-bottom: 10px;">
                        {{ Form::open(array('route' => array('comment.destroy', $comment->id), 'method' => 'delete', 'class' => 'inline')) }}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        @endforeach
        {{ $comments->links() }}
    </div>
@stop